# Workflow name
name: Build and Publish Storybook to GitHub Pages

on:
  release:
    types: [created]

permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.2
        with:
          path: build # change to your build folder
